name: CI

on:
  push:
    branches:
      - main
      - master
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.2
          bundler-cache: true

      - name: Install SQLite dependencies
        run: sudo apt-get update && sudo apt-get install -y libsqlite3-dev

      - name: Install dependencies
        run: bundle install --jobs 4 --retry 3

      - name: Ensure bin/rails is executable
        run: chmod +x bin/rails

      - name: Generate test database config
        run: |
          cat > config/database.yml <<-YAML
          test:
            adapter: sqlite3
            database: db/test.sqlite3
            pool: 5
            timeout: 5000
          YAML

      - name: Prepare database
        run: bin/rails db:drop db:create db:schema:load RAILS_ENV=test

      - name: Run RSpec tests
        env:
          RAILS_ENV: test
        run: |
          if bundle exec rspec --version > /dev/null 2>&1; then
            bundle exec rspec
          else
            echo "RSpec not found, skipping..."
          fi

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.2
          bundler-cache: true

      - name: Ensure rubocop is executable
        run: chmod +x bin/rubocop

      - name: Lint code for consistent style
        run: bin/rubocop -f github

  scan_ruby:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.2
          bundler-cache: true

      - name: Ensure brakeman is executable
        run: chmod +x bin/brakeman

      - name: Scan for common Rails security vulnerabilities using static analysis
        run: bin/brakeman --no-pager
